Exclude non avail func
YutaroHayakawa/ipftrace pull request #10
Opened 2020-03-05 13:00 UTC by mmisono

When I ran ipftrace (on Linux 5.5, which I built), I saw the following
warnings.

```
% sudo ipftrace -p ICMP linux5.5.yaml
Loading module "Default"
cannot attach kprobe, Invalid argument
Couldn't attach kprobe to function nla_append
cannot attach kprobe, Invalid argument
Couldn't attach kprobe to function nla_put_nohdr
Couldn't attach kprobe to function nla_put_64bit
cannot attach kprobe, Invalid argument
[...]
```

After some investigation, I found that `nla_append` (and other
some funcations) was not listed in
/sys/kernel/debug/tracing/available_filter_functions, which mean that
the function was not traceable (with ftrace). I really not sure why the
function is not traceable. The function is not marked with notrace nor
inlined.

Anyway, kernel BTF includes information on functions marked with
notrace. In addition, it is possible for a manifest file to contain
function names not available in a tracee kernel. Exclude these non
traceable functions by consulting
/sys/kernel/debug/tracing/available_filter_functions.

2020-03-05 14:57 UTC, YutaroHayakawa requested changes
Thank you very much for your contribution. LGTM with a nit.

2020-03-05 14:57 UTC, YutaroHayakawa commented on ipftrace/ipftrace.py
> +        available = []
Nit: `X in List` has O(N) time complexity. It would be nice to use Set instead of it.

2020-03-05 22:01 UTC, mmisono commented
@YutaroHayakawa Updated.

2020-03-07 06:41 UTC, merged

2020-03-07 06:41 UTC, YutaroHayakawa commented
Thanks! Merged.